version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 539228799627.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build  -t aws_cicd_ecr/java .
      - docker tag aws_cicd_ecr/java:latest 539228799627.dkr.ecr.ap-northeast-1.amazonaws.com/aws_cicd_ecr/java:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 539228799627.dkr.ecr.ap-northeast-1.amazonaws.com/aws_cicd_ecr/java:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '{"ImageURI":"539228799627.dkr.ecr.ap-northeast-1.amazonaws.com/aws_cicd_ecr/java:$CODEBUILD_RESOLVED_SOURCE_VERSION"}' > imageDetail.json
      - cat imageDetail.json
artifacts:
  files: 
    - imageDetail.json
    - taskdef.json
    - appspec.yaml
